# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes

# Handling Reading
safe:         false
keep_files:   [".git", ".svn"]
include:      [".htaccess", "_pages", "tags"]
exclude:      ["Gemfile", "Gemfile.lock"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist:
  - jekyll-redirect-from
gems:
  - jekyll-paginate
  - jekyll-redirect-from

# Conversion
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink:     /:title.html
paginate: 10
paginate_path: /posts/:num
timezone:      null

# Collections
collections:
  projects:
    output: true
  graphics:
    output: true

quiet:    false
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/posts/:year-:month-:day-:title.html"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      permalink: "/projects/:title.html"
  -
    scope:
      path: ""
      type: "tags"
    values:
      layout: "tags"
      permalink: "/tags/:tag"
  -
    scope:
      path: ""
      type: "graphics"
    values:
      layout: "graphic"
      permalink: "/graphics/:year-:month-:day-:title.html"

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  math_engine: mathjax

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
